spring:
  application:
    name:
      wise-task-event
  security:
    jwt:
      public-key: classpath:certs/public.pem
  r2dbc:
    username: wise_task_event
    password: wise_task_event
    url: r2dbc:postgresql://wise-task-event-db:5433/wise_task_event
    pool:
      enabled: true
  cache:
    type: none
#    caffeine:
#      spec: maximumSize=1000,expireAfterWrite=1m
#    cache-names: statistics
  liquibase:
    url: jdbc:postgresql://wise-task-event-db:5433/wise_task_event
    user: wise_task_event
    password: wise_task_event
    change-log: classpath:liquibase/change-log-master.yaml
    enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO

grpc:
  server:
    port: 6569
    reflection-service-enabled: true

wise-task-event:
  statistics:
    time-to-live: 1

server:
  port: 8085