spring:
  application:
    name:
      wise-task-event
  security:
    jwt:
      public-key: classpath:certs/public.pem
  r2dbc:
    username: ${EVENT_DB_USER}
    password: ${EVENT_DB_PASSWORD}
    url: r2dbc:postgresql://${EVENT_DB_APP_NAME}:${EVENT_DB_PORT}/${EVENT_DB}
    pool:
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: ${CACHE_SPEC}
    cache-names: statistics
  liquibase:
    url: jdbc:postgresql://${EVENT_DB_APP_NAME}:${EVENT_DB_PORT}/${EVENT_DB}
    user: ${EVENT_DB_USER}
    password: ${EVENT_DB_PASSWORD}
    change-log: classpath:liquibase/change-log-master.yaml
    enabled: true

logging:
  level:
    ru.leti.wise.task.event: ${LOGGING_LEVEL}
    org.springframework.security: ${LOGGING_LEVEL}
    org.springframework.web: ${LOGGING_LEVEL}

grpc:
  server:
    port: ${EVENT_GRPC_PORT}

wise-task-event:
  statistics:
    time-to-live: ${TIME_TO_LIVE_SECONDS}

server:
  port: ${EVENT_PORT}