syntax = "proto3";
package ru.leti.wise.task.event;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service StatisticsService{
  rpc GetSuccessRate(SuccessRateRequest) returns (StatisticResponse) {};
  rpc GetSum(SumRequest) returns (StatisticResponse) {};
  rpc GetMean(MeanRequest) returns (StatisticResponse){};
}

message MeanRequest{
  string event_type = 1;
  oneof entity{
    string task_id = 2;
    string user_id = 3;
  }
}

message SumRequest{
  string event_type = 1;
  oneof relyOn {
    string task_id = 2;
    string user_id = 3;
    Session session = 4;
  }
}


message SuccessRateRequest {
  oneof relyOn {
    string task_id = 1;
    string user_id = 2;
    Session session = 3;
  }
}

message Session{
  string id = 1;
  string user_id = 2;
  string task_id = 3;
}

message StatisticResponse{
  StatisticScope scope = 1;
  StatisticType type = 2;
  google.protobuf.Timestamp update_at = 3;
  oneof relyOn{
    string task_id = 4;
    string user_id = 5;
    Session session = 6;
  }
  double value = 7;
  string event_type = 8;
}

enum StatisticScope {
  USER = 0;
  TASK = 1;
  SESSION = 2;
}

enum StatisticType {
  SUCCESS_RATE = 0;
  SUM = 1;
  MEAN = 2;
}